[package]
name = "idns-eth-sdk-ffi"
version = "0.1.0"
edition = "2021"


[lib]
name = "idns_eth_sdk_ffi"
crate-type = ["staticlib"]

[dependencies]


#IDNS.ETH
idns-eth-sdk = { path = "../sdk", version = "*" }
